<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advocate Defendant' => '',
    'Advocate Plaintiff' => '',
    'Are you sure you want to delete this item?' => '',
    'Attachment' => '',
    'Author' => '',
    'COURT OF APPEAL' => '',
    'Case No' => '',
    'Case Number' => '',
    'Category' => '',
    'Cause Lists' => '',
    'Commercial Court' => '',
    'Congratulations' => '',
    'Courts' => '',
    'Create Cause List' => '',
    'Create Divisions' => '',
    'Create Judgments' => '',
    'Create Posts' => '',
    'Create Source Message' => '',
    'Create Vacancies' => '',
    'Create Zones' => '',
    'Dates' => '',
    'Delete' => '',
    'Descriptions' => '',
    'Division' => '',
    'Divisions' => '',
    'Duties' => '',
    'HIGH COURT DIVISIONS' => '',
    'HIGH COURT MAIN REGISTRY' => '',
    'HIGH COURT ZONES' => '',
    'High court division of corruption and economic crimes' => '',
    'ID' => '',
    'Judgments' => '',
    'Labour Court' => '',
    'Land Court' => '',
    'Location' => '',
    'Message' => '',
    'Parties' => '',
    'Please fill out the following fields to login' => '',
    'Position' => '',
    'Posted By' => '',
    'Posts' => '',
    'RESIDENT MAGISTRATES COURTS' => '',
    'RMs Courts' => '',
    'Reset' => '',
    'Save' => '',
    'Search' => '',
    'Source Messages' => '',
    'The requested page does not exist.' => '',
    'Time' => '',
    'Title' => '',
    'Type' => '',
    'Update' => '',
    'Update Cause List: {nameAttribute}' => '',
    'Update Divisions: {nameAttribute}' => '',
    'Update Judgments: {nameAttribute}' => '',
    'Update Posts: {nameAttribute}' => '',
    'Update Source Message: {nameAttribute}' => '',
    'Update Vacancies: {nameAttribute}' => '',
    'Update Zones: {nameAttribute}' => '',
    'Uploads' => '',
    'Vacancies' => '',
    'View Cause Lists' => '',
    'View Judgments' => '',
    'Witness' => '',
    'You have successfully created your Yii-powered application' => '',
    'Zone' => '',
    'Zone ID' => '',
    'Zones' => '',
    'Create Message' => '@@@@',
    'Language' => '@@@@',
    'Messages' => '@@@@',
    'Translation' => '@@@@',
    'Update Message: {nameAttribute}' => '@@@@',
];
