<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message/extract' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'Advocate Defendant' => '',
    'Advocate Plaintiff' => '',
    'Are you sure you want to delete this item?' => '',
    'Attachment' => '',
    'COURT OF APPEAL' => 'Mahakama ya Rufaa',
    'Case No' => 'Kesi Namba',
    'Case Number' => 'Namba ya Kesi',
    'Cause Lists' => 'Orodha ya Mashauri',
    'Commercial Court' => 'Mahakama ya Biashara',
    'Courts' => 'Mahakama',
    'Create Cause List' => '',
    'Create Divisions' => '',
    'Create Judgments' => '',
    'Create Vacancies' => '',
    'Create Zones' => '',
    'Dates' => 'Tarehe',
    'Division' => 'Divisheni',
    'Divisions' => 'Divisheni',
    'Duties' => '',
    'HIGH COURT DIVISIONS' => 'Divisheni za Mahakama Kuu',
    'HIGH COURT MAIN REGISTRY' => 'Masijala Kuu',
    'HIGH COURT ZONES' => 'Kanda za Mahakama kuu',
    'High court division of corruption and economic crimes' => '',
    'Judgments' => 'Hukumu',
    'Labour Court' => 'Mahakama ya Kazi',
    'Land Court' => 'Mahakama ya Ardhi',
    'Location' => 'Eneo',
    'Message' => '',
    'Parties' => '',
    'Please fill out the following fields to login' => '',
    'Position' => '',
    'Posted By' => '',
    'RESIDENT MAGISTRATES COURTS' => 'Mahakama ya Hakimu Mkazi',
    'RMs Courts' => 'Mahakama ya Hakimu Mkazi',
    'Reset' => '',
    'Source Messages' => '',
    'The requested page does not exist.' => '',
    'Time' => 'Muda',
    'Type' => '',
    'Update' => '',
    'Update Cause List: {nameAttribute}' => '',
    'Update Divisions: {nameAttribute}' => '',
    'Update Judgments: {nameAttribute}' => '',
    'Update Posts: {nameAttribute}' => '',
    'Update Source Message: {nameAttribute}' => '',
    'Update Vacancies: {nameAttribute}' => '',
    'Update Zones: {nameAttribute}' => '',
    'Uploads' => '',
    'Vacancies' => '',
    'View Cause Lists' => '',
    'View Judgments' => '',
    'Witness' => '',
    'Zone' => '',
    'Zone ID' => '',
    'Zones' => '',
    'Create Message' => '@@Tengeneza maana@@',
    'Language' => '@@Lugha@@',
    'Messages' => '@@@@',
    'Translation' => '@@@@',
    'Update Message: {nameAttribute}' => '@@@@',
    'Author' => 'Mwandishi',
    'Category' => 'Aina',
    'Congratulations' => 'Hongera',
    'Create Posts' => 'Tengeneza waraka',
    'Create Source Message' => 'Tengeneza jumbe',
    'Delete' => 'Futa',
    'Descriptions' => 'Maelezo',
    'ID' => 'Usajili',
    'Posts' => 'Nyaraka',
    'Save' => 'Hifadhi',
    'Search' => 'Tafuta',
    'Title' => 'Kichwa cha habari',
    'You have successfully created your Yii-powered application' => 'Umefanikiwa kutengeneza mradi wako wa Yii',
];
